--사용자 테이블
CREATE TABLE in_users (
    iuser_id NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY, -- 사용자 고유 ID
    iuser_password VARCHAR2(100) NOT NULL, -- 사용자 비밀번호 (암호화 고려)
    iuser_role VARCHAR2(50) CHECK (iuser_role IN ('admin', 'contractor')), -- 사용자 역할
    iuser_phone VARCHAR2(20) -- 전화번호 (옵션)
);

--시공 사례 테이블
CREATE TABLE in_projects (
    iproject_id NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY, -- 시공 사례 고유 ID
    iproject_user_id NUMBER, -- 업자 ID (외래 키, NULL 허용으로 수정됨)
    iproject_name VARCHAR2(255) NOT NULL, -- 작성자 이름
    iproject_title VARCHAR2(255) NOT NULL, -- 시공 사례 제목
    iproject_text CLOB, -- 시공 사례 설명 (컬럼명 변경됨)
    iproject_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 업로드 일시
    CONSTRAINT fk_iproject_user FOREIGN KEY (iproject_user_id) REFERENCES in_users(iuser_id) ON DELETE CASCADE
);

CREATE SEQUENCE in_projects_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

--사진 테이블(시공 사례, 후기)
CREATE TABLE in_photos (
    iphoto_id NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY, -- 사진 고유 ID
    iphoto_project_id NUMBER NULL, -- 시공 사례 ID (참조 가능)
    iphoto_review_id NUMBER NULL, -- 리뷰 ID (참조 가능)
    iphoto_filename VARCHAR2(255) NOT NULL, -- 저장된 파일명 (UUID 추천)
    iphoto_extension VARCHAR2(10) NOT NULL, -- 파일 확장자
    iphoto_uploaded_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- 업로드 일시
    CONSTRAINT fk_iphoto_project FOREIGN KEY (iphoto_project_id) REFERENCES in_projects(iproject_id) ON DELETE CASCADE,
    CONSTRAINT fk_iphoto_review FOREIGN KEY (iphoto_review_id) REFERENCES in_reviews(ireview_id) ON DELETE CASCADE,
    CONSTRAINT chk_iphoto_reference CHECK (
        iphoto_project_id IS NOT NULL OR iphoto_review_id IS NOT NULL
    )
);

-- 중복 저장 방지를 위한 유니크 제약
ALTER TABLE in_photos ADD CONSTRAINT uq_iphoto_filename UNIQUE (iphoto_filename);

--견적 문의 테이블
CREATE TABLE in_estimate (
    iesti_id NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY, -- 견적 문의 고유 ID
    iesti_name VARCHAR2(255) NOT NULL, -- 작성자 이름
    iesti_phone VARCHAR2(20) NOT NULL, -- 전화번호 (컬럼명 변경 및 타입 변경)
    iesti_title VARCHAR2(255) NOT NULL, -- 제목
    iesti_request_text CLOB NOT NULL, -- 문의 내용
    iesti_status VARCHAR2(50) DEFAULT '견적 문의' CHECK (
        iesti_status IN ('견적 문의', '시공 진행', '시공 완료')
    ), -- 상태
    iesti_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- 작성일
);

--시공 후기 테이블
CREATE TABLE in_reviews (
    ireview_id NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY, -- 리뷰 고유 ID
    ireview_name VARCHAR2(255) NOT NULL, -- 작성자 이름
    ireview_phone VARCHAR2(20) NOT NULL, -- 전화번호 (컬럼명 변경 및 타입 변경)
    ireview_title VARCHAR2(255) NOT NULL, -- 제목
    ireview_text CLOB NOT NULL, -- 내용
    ireview_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 작성일
    ireview_types VARCHAR2(255) -- 시공 항목 (쉼표 구분된 값)
);

CREATE SEQUENCE in_reviews_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
